/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/About.vue')['default']
    Dashboard: typeof import('./src/components/Dashboard.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    MazCard: typeof import('maz-ui/components')['MazCard']
    MazDialog: typeof import('maz-ui/components')['MazDialog']
    MazSelect: typeof import('maz-ui/components')['MazSelect']
    MazTabs: typeof import('maz-ui/components')['MazTabs']
    MazTabsBar: typeof import('maz-ui/components')['MazTabsBar']
    MazTabsContent: typeof import('maz-ui/components')['MazTabsContent']
    MazTabsContentItem: typeof import('maz-ui/components')['MazTabsContentItem']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    Spinner: typeof import('./src/components/Spinner.vue')['default']
    SummaryTable: typeof import('./src/components/SummaryTable.vue')['default']
  }
}
