/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/About.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    MazBtn: typeof import('maz-ui/components')['MazBtn']
    MazCard: typeof import('maz-ui/components')['MazCard']
    MazFullscreenLoader: typeof import('maz-ui/components')['MazFullscreenLoader']
    MazSelect: typeof import('maz-ui/components')['MazSelect']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    Spinner: typeof import('./src/components/Spinner.vue')['default']
    SummaryTable: typeof import('./src/components/SummaryTable.vue')['default']
  }
}
